apiVersion: v1
kind: Secret
metadata:
  name: cd2024test-dev-db-secret
  annotations:
    "helm.sh/resource-policy": "keep"  
data:
  password: {{  "cd2024test"  | b64enc }}
  user: {{ "postgres" | b64enc }}
  postgresql-password: {{  "cd2024test"  | b64enc }}

